### PR TITLE
add timestamp to EMG API (backwards compatible)

### PR DESCRIPTION
**Pull request by superkruger**

### CODE REVIEW

**Comment by smngreenberg** [comment]
Thanks for the PR! I think we'll want to uniformly include the timestamp for all events (not just EMG) before merging this in. Would you mind updating? 

We'll also update the README when this is in.

**Comment by superkruger** [comment]
No prob Scott,

I'll update both.

Jaco

On Tue, Mar 31, 2015 at 7:28 AM, Scott Greenberg notifications@github.com
wrote:

> Thanks for the PR! I think we'll want to uniformly include the timestamp
> for all events (not just EMG) before merging this in. Would you mind
> updating?
> 
> We'll also update the README when this is in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thalmiclabs/myo.js/pull/8#issuecomment-87822347.

## 

Jaco Kruger
Email: superkruger@gmail.com
Cell: +61(0)481 084 750
Skype: super.kruger

**Comment by superkruger** [comment]
Hey Scott, not sure if the last commit to this PR was seen 8 days ago...

**Comment by smngreenberg** [comment]
Woops, sorry! Merging now, thanks again.

**Comment by superkruger** [comment]
Small addition :) but loving the myo more and more...

On Thursday, April 9, 2015, Scott Greenberg notifications@github.com
wrote:

> Woops, sorry! Merging now, thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thalmiclabs/myo.js/pull/8#issuecomment-90935673.

## 

Jaco Kruger
Email: superkruger@gmail.com
Cell: +61(0)481 084 750
Skype: super.kruger

**Comment by smngreenberg** [comment]
Glad to hear it! :)

**Pull request merged**
